### PR TITLE
15 add containerization to the project

### PR DESCRIPTION
**Pull request by mjza**
I made a docker file based on my knowledge.
The problem is I must be able to run your program first, then create the docker.
But the installation and How to run were not part of your document.
Maybe we need to modify the `Dockerfile` but the backbone is correct.

### CODE REVIEW

**Comment by minaoar** [comment]
As outlined in the Contributing file, the [Contributor License Agreement](https://github.com/minaoar/library-version-wise-opinion-extration/blob/main/Contributor_License_Agreement.md) needs to be signed and sent through email before any source code contribution.

**Comment by mjza** [comment]
As I see you changed the policy, please let me know if there are any other barrier for accepting this pull request.

**Comment by minaoar** [comment]
Hi Mahdi, I will test the changes in my machine and then merge the PR. I am planning to do it by this week. Thanks for your follow up, appreciate it :)

**Comment by minaoar** [comment]
Hi [Mahdi](@mjza), could you please check if you can now run the containerized scripts?
If you run data_collection.py, it should give you some text output which are extracted opinions about some library. Please note that the output can vary in different executions.

**Comment by mjza** [comment]
I have checked and it works.

**Pull request merged**
